name: Build, Test and Deploy Denison Social backend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploying on EC2 via SSH
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploying Application on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_EC2_IP }}
        username: ${{ secrets.SSH_EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          cd denison-social
          ./docker-ec2-deploy.sh