name: Build, Test and Deploy Denison Social backend

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Injecting env vars
      run: |
        touch .env
    - name: Building Docker containers
      run: |
        docker-compose up --detach --build
        docker-compose logs
