name: Build and deploy frontend

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./denison-social-ui
    steps:
      - uses: actions/checkout@v2

      - name: Injecting environment variables
        run: echo "REACT_APP_API_URL=${{ secrets.API_URL }}" > .env

      - name: Installing dependencies
        run: npm install

      - name: Building project
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy to S3 bucket
        run: aws s3 sync ./build/ s3://denison-social --delete